name: Build and Release Go Binary

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # 根据需要添加其他权限

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # 指定需要的 Go 版本

      - name: Build the binary
        run: go build -v ./...

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Release description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}