name: 构建 Go 二进制文件

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置 Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: 编译二进制文件
      run: |
        go build -v -o composeImage ./...