name: 构建 Go 二进制文件

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 缓存 Go 模块
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: 设置 Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: 编译二进制文件
      run: |
        go build -v -o composeImage ./...