name: Build and Release Go Binary

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
    permissions:
      contents: write

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: 设置环境变量
        run: |
          echo "GOOS=${{ matrix.os }}" >> $GITHUB_ENV
          echo "GOARCH=amd64" >> $GITHUB_ENV

      - name: 编译程序
        run: |
          mkdir -p build
          go build -o build/myapp-${{ matrix.os }}-amd64

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: myapp-${{ matrix.os }}-amd64
          path: build/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 下载构建产物
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: 创建 Release 并上传资产
        uses: ncipollo/release-action@v1
        with:
          artifacts: './artifacts/**'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: 自动生成的发布
          draft: false
          prerelease: false
